use kubeconfig directly

diff --git a/.github/workflows/push_and_deploy_to_ionos.yaml b/.github/workflows/push_and_deploy_to_ionos.yaml
--- a/.github/workflows/push_and_deploy_to_ionos.yaml
+++ b/.github/workflows/push_and_deploy_to_ionos.yaml
@@ -49,32 +49,32 @@ jobs:
               KUBECONFIG: $HOME/.kube/temp-config.yaml
 
         - name: Verify kubectl configuration
-          env:
-            KUBECONFIG: $HOME/.kube/temp-config.yaml
           run: |
-            kubectl config view
-            kubectl config get-contexts
-            kubectl config current-context
-            kubectl config view > config_output.txt
-            if ! grep -q "ivicosregistry.cr.de-fra.ionos.com" config_output.txt; then
-              echo "Error: kubectl configuration does not match IONOS configuration"
-              exit 1
-            fi
+              KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl config view
+              KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl config get-contexts
+              KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl config current-context
+              if ! KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl config view | grep -q "ivicosregistry.cr.de-fra.ionos.com"; then
+                  echo "Error: kubectl configuration does not match IONOS configuration"
+                exit 1
+              fi
 
         - name: Check if Kubernetes secret exists
           id: check-secret
           run: |
-            kubectl --kubeconfig $HOME/.kube/temp-config get secret ionossecretasad || echo "Secret does not exist"
+            if KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl get secret ionossecretasad; then
+              echo "exists=true" >> $GITHUB_ENV
+            else
+              echo "exists=false" >> $GITHUB_ENV
+            fi
 
         - name: Create Kubernetes secret for Docker registry if it does not exist
-          if: steps.check-secret.outputs.result == 'Secret does not exist'
+          if: env.exists == 'false'
           env:
             IONOS_TOKEN_NAME: ${{ secrets.IONOS_TOKEN_NAME }}
             IONOS_TOKEN_PASSWORD: ${{ secrets.IONOS_TOKEN_PASSWORD }}
             IONOS_EMAIL: ${{ secrets.IONOS_EMAIL }}
-            KUBECONFIG: $HOME/.kube/temp-config.yaml
           run: |
-            kubectl --kubeconfig $HOME/.kube/temp-config create secret docker-registry ionossecretasad \
+            KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl create secret docker-registry ionossecretasad \
               --docker-server=ivicosregistry.cr.de-fra.ionos.com \
               --docker-username=$IONOS_TOKEN_NAME \
               --docker-password=$IONOS_TOKEN_PASSWORD \
@@ -82,6 +82,5 @@ jobs:
 
         # Step to create deployment to IONOS Kubernetes
         - name: Apply Kubernetes manifests
-          env:
-            KUBECONFIG: $HOME/.kube/temp-config.yaml
-          run: kubectl apply -f web-app.yaml
+          run: |
+            KUBECONFIG=$HOME/.kube/temp-config.yaml kubectl apply -f web-app.yaml
